# GET  http://localhost:7000/todos/

# PUT http://localhost:7000/todos/61d672b63a940338e6061087

# {
#   "title": "New Title",
#   "completed": true
# }


POST http://localhost:7000/todos/ HTTP/1.1

{
  "title": " A New Title",
  "description": "New Description",
}

# PUT http://localhost:7000/todos/61d7199c5c1c44e057227040 HTTP/1.1
# content-type: application/json

# {
#   "title": "PUT Title",
#   "description": "PUT Description",
# }